export const SET_AUTH_TOKEN = 'SET_AUTH_TOKEN';
export const SET_NEW_USER = 'SET_NEW_USER';
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED';
export const SET_USER_LIST = 'SET_USER_LIST';
export const APPEND_USER_LIST= 'APPEND_USER_LIST';
export const SET_USER_FROM_USER_LIST = 'SET_USER_FROM_USER_LIST';
export const SET_USER = 'SET_USER';
export const SET_USER_NAME = 'SET_USER_NAME';
export const SET_USER_DATA = 'SET_USER_DATA';
export const GENERIC_USER_FIELD_SET = 'GENERIC_USER_FIELD_SET';
export const SET_USER_TYPE = 'SET_USER_TYPE';
export const SET_INITIAL_LOGIN_OFF = 'SET_INITIAL_LOGIN_OFF';
export const SET_INCOMING_CALL = 'SET_INCOMING_CALL';
export const SET_CALL_ACTIVE = 'SET_CALL_ACTIVE';
export const END_CALL = 'END_CALL';
export const SET_PACKAGES = 'SET_PACKAGES';
export const UPDATE_PACKAGE = 'UPDATE_PACKAGE';
export const REMOVE_PACKAGE = 'REMOVE_PACKAGE';
export const SET_SLOTS = 'SET_SLOTS';
export const SET_MY_SUBSCRIPTIONS = 'SET_MY_SUBSCRIPTIONS';
export const SET_GLOBAL_SLOTS = 'SET_GLOBAL_SLOTS';
export const SET_MY_APPOINTMENTS = 'SET_MY_APPOINTMENTS';
export const SET_ACTIVITIES = 'SET_ACTIVITIES';

export const SET_POSTS = 'SET_POSTS';
export const SET_POST = 'SET_POST';
export const APPEND_POSTS = 'APPEND_POSTS';
export const REMOVE_POST = 'REMOVE_POST';
export const REMOVE_QUESTION = 'REMOVE_QUESTION';
export const SET_POSTS_FOR_USER = 'SET_POSTS_FOR_USER';
export const SET_QUESTIONS = 'SET_QUESTIONS';
export const SET_QUESTION = 'SET_QUESTION';
export const APPEND_QUESTIONS = 'APPEND_QUESTIONS';

export const SET_BMI_RECORDS = 'SET_BMI_RECORDS';
export const ADD_BMI_RECORD = 'ADD_BMI_RECORD';
export const SET_COUPONS ='SET_COUPONS';
export const APPEND_COUPONS ='APPEND_COUPONS';
export const SET_PREFERENCES ='SET_PREFERENCES';
export const SET_EXERCISE_INDEX ='SET_EXERCISE_INDEX';
export const SET_TARGET ='SET_TARGET';


export const RESET_APP = 'RESET_APP';