export const coachedPeople = (amount) => `Coached ${amount} people`;
export const durationBuilder = (duration) => `DURATION: ${duration} Weeks`;
export const priceBuilder = (price) => `PRICE: ${price} INR`;
export const subscribedSuccessBuilder = (trainerName, sessionCount) => `Successfully subscribed to ${trainerName} for ${sessionCount} sessions`;
export const appointmentSuccessBuilder = () => `Appointment Booked`;
export const appointmentErrorBuilder = () => `Booking error, try again`;
export const couponShareBuilder = (couponCode, discount,validTill) => `Hello, use my coupon ${couponCode} to avail ${discount}% on all my packages! Valid till ${validTill}`;
const strings = {
  SLOTS: 'Slots',
  AVAILABLE_SLOTS: 'Available Slots',
  PACKAGE_NAME: 'Package Name',
  MINS: 'Mins',
  DATE: 'Date',
  ALLOTTED_TO: 'Allotted to ',
  CONFIRM_FLAG: 'Report Content?',
  NO_SLOTS_AVAILABLE: 'No slots available',
  RUNNING_DAYS: 'Running WorkoutDays',
  POST: 'Post',
  DONE: 'Done',
  ADD_POST: 'Add Post',
  NO_ACTIVITY: 'No activity found',
  ADD_IMAGE: 'Add Image',
  NEW_POSTS: 'New Posts',
  CHANGE_IMAGE: 'Change Image',
  RUPEE: '₹',
  PACKAGE_CREATED: 'Package Created',
  FOLLOW: 'Follow',
  COMMENTS: 'Comments',
  COMMENT: 'Comment',
  CHANGES_SAVED: 'Changes Saved',
  TIMING: 'Timing',
  PACKAGE_SUMMARY: 'Package Summary',
  BOOK: 'Book',
  RINGING: 'Ringing',
  BOOKED: 'Booked',
  EDIT_COVER: 'Edit Cover',
  ENROLL: 'Enroll',
  NO_OF_SESSIONS: 'Number of Sessions',
  MY_PACKAGES: 'My Packages',
  MY_SLOTS: 'My Slots',
  NEW_APPOINTMENT: 'New Appointment',
  MY_CLIENTS: 'My Clients',
  PACKAGES: 'Packages',
  SESSIONS: 'Sessions',
  FOLLOWERS: 'Followers',
  PLAN_DESCRIPTION: 'Plan description',
  FOLLOWING: 'Following',
  TRANSFORMATIONS: 'Transformations',
  NO_DESC: "No description provided for this user",
  MAKEOVERS: 'Makeovers',
  SCHEDULE: 'Schedule',
  RATING: 'Rating',
  SEE_MORE: 'See more',
  SEE_LESS: 'See less',
  SUBSCRIPTIONS: 'Subscriptions',
  SUBSCRIBE: 'Subscribe',
  SOCIAL: 'Social',
  POSTS: 'Posts',
  DURATION: 'Duration',
  PROGRAMS: 'Programs',
  WEEKS: 'Weeks',
  PRICE: 'PRICE',
  PRICE_TITLE: 'Price',
  DESCRIPTION: 'Description',
  PLAN_PRICE: 'Plan price :',
  PROCEED: 'Proceed',
  CALL: 'Call',
  WAITING_FOR_USERS: 'Waiting for user to join',
  CALL_TIMEOUT: 'Call timeout, ending call.',
  APPOINTMENTS: 'Appointments',
  SIGNUP_FAILED: 'Signup Failed..Try Again',
  LOGIN_FAILED: 'Login Failed..Try Again',
  SLOT_BOOKING_SUCCESS: "Slot booked!",
  SLOT_BOOKING_ERROR: 'Unable to book slot, try again',
  QUESTION: 'Question',
  QUESTIONS: 'Questions',
  ANSWERED_BY: 'Answered by,',
  ANSWER: 'Answer',
  CANCEL: 'Cancel',
  ASK_EXPERT: 'Ask an expert',
  USER_DETAILS: 'User Details',
  NAME: 'Name',
  BOOKING_DATE: 'Booking Date',
  TRAINER_DETAILS: 'Trainer Details',
  PACKAGE_DETAILS: 'Package Details',
  SUBSCRIPTION_DETAILS: 'Subscription Details',
  SESSION_DETAILS: 'Session Details',
  TRAINER: 'Trainer',
  SESSION_TIME: 'Session time',
  START_FROM: 'Start from',
  END_AT: 'End at',
  TOTAL_SESSIONS: 'Total Sessions',
  SESSION_DAYS: 'Session WorkoutDays',
  CREATE: 'Create',
  NO_DATA: 'No Data',
  DAYS:'How many days do you work out per week?',
  PREFERENCES: 'Preferences',
  DESCRIBEDAYS:'This describe the number of days in your workout plan',
  BMI_CALCULATOR: 'BMI Calculator',
  HISTORY: 'History',
  SET_TARGET: 'Set Target',
  NEW_WEIGHT: 'NEW WEIGHT',
  COUPONS: 'Coupons',
  COUNT: 'Count',
  DISCOUNT: 'Discount',
  VALIDITY: 'Validity',
  GENERATE: 'Generate',
  COUPON_CODE: 'Coupon Code',
  REDEEMED: 'Redeemed',
  COUPONS_CREATED: 'Coupons created',
  ENTER_COUPON_CODE: 'Apply Coupon Code',
  APPLY: 'Apply',
  TOTAl: 'Total',
  WORKOUT:'Workout Video',
  CHANGE_VIDEO : 'Change Video',
  ADD_VIDEO:'Add Video',
  PHYSICAL_DATA: 'Physical Data',
  WEIGHT: 'Weight (kg)',
  HEIGHT:'Height (cms)',
  DELETE:'Delete',
  REPORT_CONTENT: 'Report Content',
  LAST_DAYS: 'Last few days',
  LAST_MONTHS: 'Last few months',
  ENTER_WEIGHT: 'Enter weight',
  ENTER_TARGET:'Enter target weight and goal date',
  INVALID_COUPON: 'Invalid coupon code or coupon expired'

};

export const bmiVerdicts = {
  low:`UNDERWEIGHT` ,
  healthy: `YOU'RE HEALTHY`,
  high:`OVERWEIGHT`,
  unhealthy:`OBESE`
}

export default strings;